name: EMNLP2020
tagline: The 58th Annual Meeting of <br> the Association for Computational Linguistics
date: Nov 16 &ndash; 20 <br> 2020
proceedings_title: Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics
citation_date: July 2020
analytics: UA-171494682-1
site_url: https://virtual.acl2020.org
logo:
  image: static/images/emnlp2020/acl-logo.png
  height: 45px
site_title: EMNLP2020
page_title:
  prefix: 'EMNLP2020'
  separator: ': '
background_image: static/images/acl2020/EMNLP-Banner-5.1.jpg
organization: Association for Computational Linguistics

# Path to the folder of paper images.
paper_images_path: https://acl2020-public.s3.amazonaws.com/papers
default_presentation_id: 38931484

# Remove or change to your chat server.
chat_server: acl2020.rocket.chat

calendar:
  start: '2020-07-05'
  end: '2020-07-10'
