name: Deploy to GitHub Pages
on:
  push:
    branches:
      - live

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.CI_TOKEN }}
        ref: 'live'

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install NPM dependencies
      run: npm ci

    - name: Build website
      run: make freeze

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:acl-org/emnlp-2020-virtual-conference.git
        BRANCH: gh-pages
        FOLDER: build
        SSH_PRIVATE_KEY: ${{ secrets.CI_TOKEN }}
